[package]
name = "rs-sloth-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
image = "0.24.7"
log = "0.4.20"
pixels = "0.13.0"
winit = "0.28.7"
